### ISSUE TITLE
Idea: Auto-Set labels based on modified path

### ISSUE THREAD

**Issue by silverwind** [GiteaBot/gitea-backporter#93]
From https://github.com/go-gitea/gitea/pull/25667#issuecomment-1620184061, I think it would be useful if the bot could auto-set some labels based on modified path. There are two kind of matching mechanisms needed:

1. If any path is modified. For example, every change in `Makefile` should get a `build` label.
2. If only a path is modified. For example a change only in `docs` should get a `kind/docs` label and maybe a `skip-changelog`, but a change that includes changes in `docs` and `templates` should not.

The config should be in the repo itself in `.github/giteabot.yaml` to be flexible to change:

```yaml
autolabels:
  only:
    - globs: [docs/**]
      labels: [kind/docs, skip-changelog]
  any:
    - globs: [Makefile]
      labels: [build]
```
